#!/usr/bin/env bash
set -euo pipefail

# Rebuild this repo's Graphify knowledge graph and mirror the generated graph
# artifacts into the Vion Obsidian vault.
#
# Defaults are intentionally local and safe to rerun:
#   - graph artifacts stay in ./graphify-out/
#   - Obsidian export is limited to the repo's dedicated vault folder
#   - without an LLM API key, the graph is code-only so the command still works
#
# Useful overrides:
#   GRAPHIFY_BIN=/path/to/graphify
#   GRAPHIFY_SEMANTIC=1        # include docs/yaml/html; requires a supported LLM key
#   GRAPHIFY_SEMANTIC=0        # force code-only extraction
#   GRAPHIFY_EXTRA_ARGS='--max-workers 4'
#   GRAPHIFY_OBSIDIAN_DIR='/path/to/vault/Vion/vion-learning'

repo_root="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
cd "$repo_root"

repo_name="$(basename "$repo_root")"
graphify_out="$repo_root/graphify-out"
obsidian_dir="${GRAPHIFY_OBSIDIAN_DIR:-/home/vion/Documents/Obsidian Vault/Vion/$repo_name}"

run_graphify() {
  if [[ -n "${GRAPHIFY_BIN:-}" ]]; then
    "$GRAPHIFY_BIN" "$@"
  elif command -v graphify >/dev/null 2>&1; then
    graphify "$@"
  elif command -v uvx >/dev/null 2>&1; then
    uvx --from graphifyy graphify "$@"
  else
    printf 'error: graphify not found and uvx is unavailable. Install with: uv tool install graphifyy\n' >&2
    exit 127
  fi
}

has_llm_key() {
  [[ -n "${GEMINI_API_KEY:-${GOOGLE_API_KEY:-}}" ]] \
    || [[ -n "${MOONSHOT_API_KEY:-}" ]] \
    || [[ -n "${ANTHROPIC_API_KEY:-}" ]] \
    || [[ -n "${OPENAI_API_KEY:-}" ]] \
    || [[ -n "${DEEPSEEK_API_KEY:-}" ]]
}

semantic_mode="${GRAPHIFY_SEMANTIC:-auto}"
extract_args=(extract "$repo_root" --out "$repo_root")

case "$semantic_mode" in
  1|true|yes|full)
    ;;
  0|false|no|code|code-only)
    extract_args+=(--exclude '*.md' --exclude 'docs/**' --exclude 'AGENTS.md' --exclude '.hermes/**' --exclude '*.yml' --exclude '*.yaml' --exclude '*.html')
    ;;
  auto)
    if ! has_llm_key; then
      printf 'No Graphify LLM API key detected; building code-only graph. Set GRAPHIFY_SEMANTIC=1 with a supported key to include docs/yaml/html.\n' >&2
      extract_args+=(--exclude '*.md' --exclude 'docs/**' --exclude 'AGENTS.md' --exclude '.hermes/**' --exclude '*.yml' --exclude '*.yaml' --exclude '*.html')
    fi
    ;;
  *)
    printf 'error: unsupported GRAPHIFY_SEMANTIC=%s (use auto, 1, or 0)\n' "$semantic_mode" >&2
    exit 2
    ;;
esac

if [[ -n "${GRAPHIFY_EXTRA_ARGS:-}" ]]; then
  # shellcheck disable=SC2206 # Intentional word splitting for CLI-style extra args.
  extra_args=(${GRAPHIFY_EXTRA_ARGS})
  extract_args+=("${extra_args[@]}")
fi

printf 'Rebuilding Graphify graph in %s ...\n' "$graphify_out"
run_graphify "${extract_args[@]}"

printf 'Regenerating Graphify report and HTML ...\n'
run_graphify cluster-only "$repo_root" --no-label

printf 'Applying Obsidian graph surface theme ...\n'
node "$repo_root/scripts/style-obsidian-graph.mjs" "$graphify_out/graph.html"

for required in "$graphify_out/graph.json" "$graphify_out/GRAPH_REPORT.md" "$graphify_out/graph.html"; do
  if [[ ! -s "$required" ]]; then
    printf 'error: expected Graphify artifact missing or empty: %s\n' "$required" >&2
    exit 1
  fi
done

printf 'Exporting Obsidian mirror to %s ...\n' "$obsidian_dir"
mkdir -p "$obsidian_dir/.obsidian"

cp "$graphify_out/GRAPH_REPORT.md" "$obsidian_dir/Graph Report.md"
cp "$graphify_out/graph.html" "$obsidian_dir/graph.html"
cp "$graphify_out/graph.json" "$obsidian_dir/.obsidian/graph.json"

index_tmp="$obsidian_dir/Graph Index.md.tmp"
cat > "$index_tmp" <<EOF
# $repo_name Graph Index

Generated by \`scripts/graphify-refresh.sh\`.

- Repo: \`$repo_root\`
- Local graph report: \`$graphify_out/GRAPH_REPORT.md\`
- Local graph HTML: \`$graphify_out/graph.html\`
- Local graph JSON: \`$graphify_out/graph.json\`
- Obsidian report mirror: [[Graph Report]]
- Obsidian HTML mirror: [graph.html](graph.html)
- Obsidian graph JSON mirror: \`.obsidian/graph.json\`

Refresh when the repo changes materially:

\`\`\`bash
scripts/graphify-refresh.sh
\`\`\`

For agent sessions: read \`graphify-out/GRAPH_REPORT.md\` first for broad orientation, use \`graphify query "<question>"\` for focused dependency questions, and only reread raw files when the graph is stale or incomplete.
EOF
mv "$index_tmp" "$obsidian_dir/Graph Index.md"

cat > "$obsidian_dir/.graphify-refresh-manifest" <<EOF
Managed by $repo_root/scripts/graphify-refresh.sh
Graph Index.md
Graph Report.md
graph.html
.obsidian/graph.json
EOF

printf 'Graphify refresh complete.\n'
printf '  graph artifacts: %s\n' "$graphify_out"
printf '  obsidian mirror: %s\n' "$obsidian_dir"
